if(WIN32)
    set(CMAKE_PLATFORM "WINDOWS")
    add_compile_definitions(DE_PLATFORM_WINDOWS)
endif()
if(UNIX AND NOT APPLE)
    set(CMAKE_PLATFORM "LINUX")
    add_compile_definitions(DE_PLATFORM_LINUX)
endif()
if(APPLE)
    set(CMAKE_PLATFORM "MACOS")
    add_compile_definitions(DE_PLATFORM_MAC)
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "Only 64-bit archetecture supported.")
endif()