#pragma once

#include <memory>
#include <iostream>
#include <iomanip>
#include <map>
#include <string>
#include <unordered_set>
#include <unordered_map>
#include <vector>
#include <filesystem>
#include <set>
#include <fstream>
#include <functional>
#include <chrono>
#include <cstdint>
#include <queue>
#include <stack>
#include <random>
#include <cxxabi.h>
#include <iostream>
#include <string_view>
#include <string>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <cstring>
#include <typeindex>

