macro(set_option option help value)
    option(${option} ${help} ${value})
    if(${option})
        message(STATUS "${option}: ON")
    else()
        message(STATUS "${option}: OFF")
    endif()
endmacro()


message(STATUS "---Confiring-Project-Options-----------------------------------------------------------------")
set_option(DE_FORMAT_BEFORE_BUILD "Runs clang-format on DummyEngine and DummyEditor before build" OFF)
set_option(DE_CLANG_TIDY_RUN_ON_COMPILATION "Run clang tidy during compilation" OFF)
set_option(DE_CLANG_TIDY_WARNINGS_AS_ERRORS "Set clang warnings as errors" OFF)
set_option(DE_FORCE_NO_PCH "Prevent PCH" OFF)
set_option(DE_ENABLE_UBSAN "Enable UBSAN" OFF)
set_option(DE_ENABLE_ASAN "Enable ASAN" OFF)
set_option(DE_ENABLE_TSAN "Enable TSAN" OFF)
set_option(DE_ENABLE_MSAN "Enable MSAN" OFF)
message(STATUS "---Confired-Project-Options------------------------------------------------------------------")
