if(WIN32)
    message(STATUS "Platform WINDOWS")
    set(DE_PLATFORM "WINDOWS")
    add_compile_definitions(DE_PLATFORM_WINDOWS)
endif()
if(UNIX AND NOT APPLE)
    message(STATUS "Platform LINUX")
    set(DE_PLATFORM "LINUX")
    add_compile_definitions(DE_PLATFORM_LINUX)
endif()
if(APPLE)
    message(STATUS "Platform MACOS")
    set(DE_PLATFORM "MACOS")
    add_compile_definitions(DE_PLATFORM_MACOS)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0" CACHE STRING "Minimum OS X deployment version")
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "Only 64-bit architecture supported.")
endif()