function(add_external_library DIRECTORY INCLUDE_DIR LIBRARY)
    message(STATUS "---Configuring-${LIBRARY}----------------------------------------------------------------------------")
    add_subdirectory(${DIRECTORY})
    set(EXTERNAL_${DIRECTORY}_INCLUDE_DIR ${INCLUDE_DIR} PARENT_SCOPE)
    set(EXTERNAL_${DIRECTORY}_LIBRARY ${LIBRARY} PARENT_SCOPE)
    message(STATUS "${DIRECTORY} include dir: ${INCLUDE_DIR}")
    message(STATUS "${DIRECTORY} library: ${LIBRARY}")
    message(STATUS "---Configured-${LIBRARY}-----------------------------------------------------------------------------")
endfunction(add_external_library)
