name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
        - uses: actions/checkout@v4
        - name: clang-format Check DummyEngine
          uses: jidicula/clang-format-action@v4.13.0
          with:
            clang-format-version: '18'
            check-path: 'DummyEngine'
        - name: clang-format Check DummyEditor
          uses: jidicula/clang-format-action@v4.13.0
          with:
            clang-format-version: '18'
            check-path: 'DummyEditor'
